In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

#### in this notebook, we are going to cover some of the most fundamental concepts of tensors using tensorflow
More specifically, we are going to cover:
* Inroduction to tensor
* Getting information from tensors
* Manupulating tensors
* Tensors and Numpy
* Using @tf.functions ( a way to speed up your regular Python functions)
* Using GPUs with Tensorflow ( or TPUs)
* Exercises to try for yourself

# Introduction To Tensors

# Import Tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


# Create tensors with tf.constant()

In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

In [4]:
scalar.ndim

0

# Create a vector

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

## Check the dimension of vector

In [6]:
vector.ndim

1

# Create a matrix ( a matrix has more than 1 dimension)

In [7]:
matrix = tf.constant([[10, 10], 
                      [5, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 5,  5]], dtype=int32)>

## Check the dimension of matrix

In [8]:
matrix.ndim

2

# Create another different matrix

In [9]:
matrix2 = tf.constant([[10., 7.], 
                      [3., 2.],
                       [8., 9.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

## Check the dimension of matrix2

In [10]:
matrix.ndim

2

# Create a tensor

In [11]:
tensor = tf.constant([[[1,2,3], 
                      [4,5,6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

## Check the dimension of tensor

In [12]:
tensor.ndim

3

### What we created so far:
- Scalar: a single number
- Vector: a number with direction (e.g. wind speed and direction)
- Matrix: a 2-dimensional array of numbers
- Tensor: an n dimensional array of numbers 

# Creating tensor with tf.Variable

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

### Create the same tensor with tf.Variable() as above

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Let's change an element in our changeable tensor

In [15]:
#changeable_tensor[0] = 7

In [16]:
changeable_tensor[0].assign(31)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([31,  7], dtype=int32)>

### Let's change an element in our unchangeable tensor


In [17]:
#unchangeable_tensor[0].assing(7)

# Creating Random Tensors

-  Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However,if in doubt, use tf.constant and change it later if needed

In [18]:
random_1 = tf.random.Generator.from_seed(42) # random_state = 42. we can change it
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a tensor

##### Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning

In [19]:
not_shuffled = tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
tf.random.set_seed(31) # random_state
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

# Other ways to make tensors

In [21]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros([10, 6])

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Numpy arrays to tensors

- The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU faster than arrays for numerical computing

In [23]:
np_A = np.arange(1, 25, dtype=np.int32) # create a np array between 1 and 25
np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(np_A, shape=(2, 3 ,4))
B = tf.constant(np_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors

- Shape: The length of each of the dimension of a tensor -> tensor.shape
- Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n -> tensor.ndim
- Axis or dimension: A particular dimension of a tensor -> tensor[0]
- Size: The total number of items in the tensor -> tf.size(tensor)


#### Create a rank 4 tensor (4 dimension): 

In [25]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
print("Shape of rank_4: {}\nDimension of rank_4: {}\nSize of rank_4:{}\nDatatype of every element: {}\nElements along the axis 0: {}\nElements along the last axis: {}".format(rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor), rank_4_tensor.dtype, rank_4_tensor.shape[0], rank_4_tensor.shape[-1] ))

Shape of rank_4: (2, 3, 4, 5)
Dimension of rank_4: 4
Size of rank_4:120
Datatype of every element: <dtype: 'float32'>
Elements along the axis 0: 2
Elements along the last axis: 5


# Indexing tensors

- Tensors can be indexed just like Python list

In [28]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# Create a rank 2 tensor

rank_2_tensor = tf.constant([[10, 6],
                            [2,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  6],
       [ 2,  3]], dtype=int32)>

In [32]:
# Get the last item of each of our rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 3], dtype=int32)>

In [33]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 6]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [34]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 6]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [35]:
tf.expand_dims(rank_2_tensor, axis = 0) # 0 means expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  6],
        [ 2,  3]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis = 1) # 1 means expand the middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  6]],

       [[ 2,  3]]], dtype=int32)>

# Manipulating tensors (tensor operations)

## Basic Operations: + - * /

In [37]:
# You can add values to  a tensor using the addition operator

tensor = tf.constant([[10, 7],
                     [3, 4]])
tensor + 10

# Original tenspr is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [40]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [41]:
# We can use TensorFlor built-in functions which are faster for big data 

tf.multiply(tensor, 5) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

# Matrix multiplication (DOT Product)

- In machine learning, matrix multiplication is one of the the most common tensor operations

In [42]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# Matix multiplication with Python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
X = tf.constant([[1, 2, 5],
                     [7, 2, 1],
                     [3, 3, 3]])

Y = tf.constant([[3, 5],
                       [6, 7],
                       [1, 8]])
print(X.shape, Y.shape)
print(tf.matmul(X, Y).shape)
tf.matmul(X, Y)

(3, 3) (3, 2)
(3, 2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [45]:
# Transpose
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [46]:
tf.reshape(Y, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

- transpose and reshape are different operations

- we can use 2 ways for dot product in tensorflow:
- * tf.matmul()
- * tf.tensordot()

In [47]:
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[7,8],
                [9, 10],
                [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [48]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [49]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [50]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
print("Normal Y:\n{}\nY reshaped to (2,3): \n{}\nTransposed Y:\n{}".format(Y, tf.reshape(Y, (2,3)), tf.transpose(Y)))

Normal Y:
[[ 7  8]
 [ 9 10]
 [11 12]]
Y reshaped to (2,3): 
[[ 7  8  9]
 [10 11 12]]
Transposed Y:
[[ 7  9 11]
 [ 8 10 12]]


- Generally, when performing matrix multiplication on two tensors and one of the axes does not line up, we will transpose ( rather than reshape) of the tensors to get satisfy the matrix multiplication rules

# Changing the datatype of tensor

In [52]:
# Create a new tensor with default datatype (float32)

B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])
B.dtype, C.dtype

(tf.float32, tf.int32)

- Today, most models usse the float32 dtype, whick takes 32 bits of memory. However, there are two lower-precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster

In [53]:
# Change from float32 to float16 (reduced precision)

D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [54]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>,
 tf.float32)

In [55]:
# Change from int32 to float16

E_float16 = tf.cast(C, dtype=tf.float16)
E_float16, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>,
 tf.float32)

# Aggregating tensors

- Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [56]:
# Get the absolute values

D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

- Let's go through the following forms of aggregation:
    * Get the minimum
    * Get the maximum
    * Get the mean of a tensor
    * Get the sum of a tensor

In [57]:
A = tf.constant(np.random.randint(1, 1000, size=50))
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([613, 820, 409, 837,  56, 202, 875, 963, 586, 355, 514,  14, 844,
       512, 526, 292, 945, 421, 134, 442, 246, 819, 708, 351, 985, 404,
       349, 381, 542, 816, 717, 634, 626, 407, 131, 932, 857, 129, 748,
       179, 205, 646, 656, 275, 292, 964, 402, 801, 199, 263])>

In [58]:
tf.size(A), A.ndim, A.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [59]:
# Get the minimum
tf.math.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [60]:
# Get the maximum
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=985>

In [61]:
# Get the mean of a tensor
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=520>

In [62]:
# Get the sum of a tensor
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int64, numpy=26024>

In [63]:
# Get the variance
# we have to convert it to float
A_float32 = tf.cast(A, dtype=tf.float32)
tf.math.reduce_variance(A_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=75427.85>

In [64]:
# Get the std
tf.math.reduce_std(A_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=274.64133>

#### Find the positional maxiumum and minimum

In [65]:
tf.random.set_seed(52)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.92698145, 0.21461594, 0.9990052 , 0.4743483 , 0.5276226 ,
       0.33547318, 0.34501696, 0.21263635, 0.9367012 , 0.99640393,
       0.20117056, 0.5211896 , 0.06967449, 0.2764392 , 0.82195294,
       0.2731073 , 0.8603343 , 0.95063424, 0.10446322, 0.13027382,
       0.8656349 , 0.17512786, 0.0454576 , 0.44055784, 0.22579014,
       0.9806918 , 0.96834946, 0.78710866, 0.420699  , 0.12642217,
       0.49817932, 0.0501039 , 0.5090022 , 0.84408104, 0.37323093,
       0.28066242, 0.8978182 , 0.7282846 , 0.94026613, 0.7336283 ,
       0.83288705, 0.8223268 , 0.33906233, 0.72157836, 0.81306946,
       0.2645644 , 0.13085485, 0.10579765, 0.29476213, 0.76393235],
      dtype=float32)>

# Find the positional maximum

In [66]:
pos_max = tf.argmax(F)
pos_max
# it gives the index fo positional maximum

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [67]:
F[pos_max]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9990052>

In [68]:
# Shortly
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9990052>

In [69]:
assert F[tf.argmax(F)] == tf.reduce_max(F)
# No error means that's correct

# Find the positional minimum

In [70]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0454576>

In [71]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0454576>

In [72]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor (removing all single dimension)

In [73]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [74]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [75]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-hot encoding tensors

In [76]:
# Create a list of indices

some_list = [0, 1, 2, 3] # could be red, green, blue, purple

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# More mathematical operations: Squaring, log, square root

In [77]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [78]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [79]:
# Square root
tf.sqrt(tf.cast(tf.square(H), dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [80]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

# Tensors and Numpy

- TensorFlow interacts beautifully with Numpy arrays

In [81]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [82]:
# Convert our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [83]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [84]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

- this might be errors while computing, be careful

# Finding access to GPUs

In [86]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]