In [1]:
import tensorflow as tf

* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [14]:
vector = tf.constant([10., 7.])
scalar = tf.constant(10)
matrix = tf.constant([[10., 7.],
                      [11, 16]])

tensor = tf.constant([
    [
        [10., 7., 3.],
         [5., 4., 3.]
        ],
     [
        [6., 5., 4.],
        [3., 2., 1.]
        ],
    [
        [1., 2., 3.],
        [4., 5., 6.]
    ]
])

scalar,vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[10.,  7.],
        [11., 16.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[10.,  7.,  3.],
         [ 5.,  4.,  3.]],
 
        [[ 6.,  5.,  4.],
         [ 3.,  2.,  1.]],
 
        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]], dtype=float32)>)

* Find the shape, rank and size of the tensors you created in 1.

In [17]:
print("Shape of tensor: {}\nRank of tensor: {}\nSize of tensor: {}".format(tensor.shape, tensor.ndim, tf.size(tensor)))

Shape of tensor: (3, 2, 3)
Rank of tensor: 3
Size of tensor: 18


* Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [29]:
random_1 = tf.constant(tf.random.uniform(minval=0, maxval=1, shape=(5,300)))
random_2 = tf.Variable(tf.random.uniform(minval=0, maxval=1, shape=(5, 300)))
random_1, random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5486244 , 0.7709118 , 0.8073604 , ..., 0.9827212 , 0.39545727,
         0.7195983 ],
        [0.7424617 , 0.5374359 , 0.9724717 , ..., 0.74005795, 0.42786264,
         0.7426647 ],
        [0.6344037 , 0.02231801, 0.649994  , ..., 0.7191012 , 0.4796425 ,
         0.21168947],
        [0.75454783, 0.6508584 , 0.64073133, ..., 0.03456092, 0.07477319,
         0.88514376],
        [0.3306867 , 0.50337934, 0.40651703, ..., 0.09679854, 0.38833594,
         0.1273315 ]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5, 300) dtype=float32, numpy=
 array([[0.9505478 , 0.67767215, 0.28040934, ..., 0.7906331 , 0.14496613,
         0.8562764 ],
        [0.26595795, 0.2533753 , 0.61897385, ..., 0.11923075, 0.9173912 ,
         0.10874856],
        [0.5988337 , 0.09842598, 0.26624477, ..., 0.36022353, 0.11457884,
         0.17654836],
        [0.39946055, 0.34142077, 0.80306685, ..., 0.19015563, 0.96765006,
         0.8431066 ],
   

* Multiply the two tensors you created in 3 using matrix multiplication.


In [32]:
tf.matmul(random_1, random_2, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[69.0794  , 69.78428 , 70.50389 , 72.67869 , 68.827965],
       [73.9797  , 78.36183 , 75.33462 , 74.74452 , 78.78995 ],
       [72.36304 , 75.79319 , 74.437965, 74.48978 , 72.38256 ],
       [73.82128 , 73.35205 , 70.16255 , 74.92376 , 73.306404],
       [73.759094, 75.65152 , 73.489204, 76.74079 , 73.54016 ]],
      dtype=float32)>

* Multiply the two tensors you created in 3 using dot product.


In [35]:
tf.tensordot(random_1, tf.transpose(random_2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[69.0794  , 69.78428 , 70.50389 , 72.67869 , 68.827965],
       [73.9797  , 78.36183 , 75.33462 , 74.74452 , 78.78995 ],
       [72.36304 , 75.79319 , 74.437965, 74.48978 , 72.38256 ],
       [73.82128 , 73.35205 , 70.16255 , 74.92376 , 73.306404],
       [73.759094, 75.65152 , 73.489204, 76.74079 , 73.54016 ]],
      dtype=float32)>

* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [36]:
random_3 = tf.random.uniform(minval=0, maxval=1, shape=(224, 224, 3))
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.29191852, 0.6509105 , 0.8507019 ],
        [0.38791287, 0.17844772, 0.21560001],
        [0.42006516, 0.6894294 , 0.5809721 ],
        ...,
        [0.97675836, 0.62121284, 0.03908062],
        [0.37908053, 0.03705502, 0.41908252],
        [0.3146044 , 0.38396192, 0.7619809 ]],

       [[0.21290958, 0.38501334, 0.863927  ],
        [0.05414033, 0.15838051, 0.16623926],
        [0.43272507, 0.9369056 , 0.40347445],
        ...,
        [0.63114154, 0.9056406 , 0.58486927],
        [0.15007567, 0.5480801 , 0.200755  ],
        [0.38837492, 0.11288393, 0.1595993 ]],

       [[0.13769901, 0.03395164, 0.61931956],
        [0.27249813, 0.87549853, 0.3900653 ],
        [0.41171694, 0.20379996, 0.7188623 ],
        ...,
        [0.23090553, 0.37314963, 0.31420386],
        [0.06096232, 0.0737915 , 0.00317645],
        [0.6459135 , 0.46993005, 0.9425    ]],

       ...,

       [[0.76626813, 0.59890866, 0.7948297 ],
        [0.93

* Find the min and max values of the tensor you created in 6 along the first axis.


In [41]:
max_val = tf.reduce_max(random_3)
min_val = tf.reduce_min(random_3)
max_val, min_val

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99999976>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.702278e-06>)

* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [45]:
random_4 = tf.random.normal(shape=(1, 224, 224, 3))
squuzed_random_4 = tf.squeeze(random_4)

random_4.shape, squuzed_random_4.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [50]:
my_tensor = tf.Variable([12, 3,2, 5, 23, 5,56,7, 1,2])
max_indeces = tf.argmax(my_tensor)
my_tensor.shape, max_indeces, my_tensor[max_indeces]

(TensorShape([10]),
 <tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=56>)

* One-hot encode the tensor you created in 9

In [51]:
tf.one_hot(my_tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>